name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: latest
          cache: "npm"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606
        with:
          toolchain: nightly,stable
          components: rustfmt,clippy

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Check for typos
        uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d
        with:
          config: ./typos.toml

      - name: Lint
        run: cargo clippy --all-features

      - name: Build
        run: cargo build --all-targets --all-features

      - name: Run tests
        run: cargo test --all-features

      - name: Check generated files are up to date
        run: |
          npm run generate
          git diff --exit-code || (echo "Generated files are out of date. Run 'npm run generate' and commit the changes." && exit 1)
